[phases.setup]
nixPkgs = ["python3"]
aptPkgs = ["libnss3", "libatk1.0-0", "libatk-bridge2.0-0", "libcups2", "libdrm2", "libxkbcommon0", "libxcomposite1", "libxdamage1", "libxrandr2", "libgbm1", "libpango-1.0-0", "asound2"]

[phases.install]
cmds = ["pip install -r requirements.txt", "playwright install chromium"]